### ISSUE TITLE
Proxy Distribution

### ISSUE THREAD

**Issue by Color-maN** [shamhi/TapSwapBot#236]
Who is more or less versed in these bots. Can you please tell me in what order the proxies are distributed to the sessions. How do I make my proxy linked to a specific session?

**Comment by dmitry-js** [comment]
Well, by default each line in `proxies.txt` is attached to each session from the `sessions` directory. E.g:
```
1.session -> type://user:pass@ip:port
2.session -> type://user2:pass@ip:port
...
```
But what will happen if you have more sessions than proxies? E.g 3 sessions and 2 proxies: 
```
1.session -> type://user:pass@ip:port
2.session -> type://user2:pass@ip:port
3.session -> ?
...
```
In that case the third session will get the first proxy from the list, the 4th -> 2nd, etc...

This approach is not flexible, because it doesn't allow to attach a proxy to a specific session name.
You need to make some code changes to make it work properly. Here's an example of how I made this in [Blum](https://github.com/dmitry-js/BlumTelegramBot/commit/f5efa3ebd30800e50cee22e5a1426a783901d2f7)

**Comment by Color-maN** [comment]
I found a pattern that proxies are distributed in the file proxies.txt (top-down) relative to sessions (top-down) sorted by Latin alphabet or numbering in the sessions folder.
