### ISSUE TITLE
Банят ли в TapSwap и Telegram аккаунт за использование этого автофарма?                                                    Are TapSwap and Telegram account banned for using this autofarm?

### ISSUE THREAD

**Issue by StevePlay2009** [shamhi/TapSwapBot#9]
Всем здравствуйте! Подскажите пожалуйста! А банят ли в TapSwap и Telegram аккаунт за использование этого автофарма? 
Я беспокоюсь просто.

Hello everyone! Please tell me! And are TapSwap and Telegram account banned for using this autofarm? 
I'm just worried.

**Comment by BraveCanister** [comment]
Did you figure it out? I used a similar script for Notcoin and it was "fine" (old account if that matters), they did take all the coins for using "scripts" but not sure if the script is at fault since other people I know who used python clicker through API access did not get banned, neither were they detected or their coins taken from them.
